apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: adapter
  name: adapter
spec:
  containers:
  - image: busybox
    name: app
    args: 
    - /bin/sh
    - -c
    - 'while true; do echo "$(date) | $(du -sh ~)" >> /var/logs/diskspace.txt; sleep 5; done;'
    volumeMounts:
      - name: var-logs
        mountPath: /var/logs
  - image: busybox
    name: transformer
    args: 
    - /bin/sh
    - -c
    - 'sleep 20; while true; do while read LINE; do echo "$LINE" | cut -f2 -d"|" >> $(date +%Y-%m-%d-%H-%M-%S)-transformed.txt; done < /var/logs/diskspace.txt; sleep 20; done;'
    volumeMounts:
      - name: var-logs
        mountPath: /var/logs
  volumes:
    - name: var-logs
      emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
