apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: backend
  name: backendsecret
spec:
  containers:
  - image: nginx
    name: backend
    envFrom:
      - secretRef:
          name: db-credentials
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
