apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
spec:
  containers:
  - image: nginx
    name: pod
    resources: {}
    env:
      - name: DB_PASSWORD
        valueFrom: 
          secretKeyRef:
            name: db-credentials
            key: db-password
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
