apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: backend
  name: backendsecretenv
spec:
  containers:
  - image: nginx
    name: backend
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: db-password
          name: db-credentials
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
