apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web
  name: web
spec:
  initContainers:
  - name: configurer
    image: busybox
    command: 
    - wget
    - "-O"
    - "/usr/shared/app/config.json"
    - https://raw.githubusercontent.com/aireddy73/Kubernetes/main/CKAD%20Exercies/07-creating-init-container/app/config/config.json
    volumeMounts:
    - mountPath: /usr/shared/app
      name: init-vol
  containers:
  - image: bmuschko/nodejs-read-config:1.0.0
    name: web
    ports:
    - containerPort: 8080
    volumeMounts:
    - mountPath: /usr/shared/app
      name: init-vol
    resources: {}
  volumes:
  - name: init-vol
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
