apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secured
  name: secured
spec:
  securityContext:
    fsGroup: 3000
  containers:
  - image: nginx
    name: secured
    resources:
      requests:
        cpu: "400m"
        memory: "200m"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
