apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxnew
  name: nginxnew
spec:
  containers:
  - image: nginx
    name: nginxnew
    envFrom:
    - configMapRef:
        name: anotherone
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
