apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: database
    env: prod
    team: storage
  name: database
spec:
  containers:
  - image: nginx
    name: database
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
