apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: busybox
        name: busybox
        command:
        - wget
        - 10.43.198.150:5678
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
status: {}
