apiVersion: batch/v1
kind: Job
metadata:
  name: whalesay
spec:
  template:
    spec:
      containers:
      - name: whalesay
        image: docker/whalesay
        command: ["cowsay I am going to acc CKAD!"]
      restartPolicy: Never
  backoffLimit: 4
  completions: 10 
