apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pi
  name: pi
spec:
  containers:
  - image: perl:5.34
    name: pi
    command: 
    - "perl Mbignum=bpi -wle 'print bpi(2000)'"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
