apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app
  name: app
  namespace: app-stack
spec:
  containers:
  - image: nginx
    name: app
    resources: {}
    volumeMounts:
      - mountPath: /var/app/config
        name: pvcclaim
  volumes:
    - name: pvcclaim
      persistentVolumeClaim:
        claimName: task-pv-claim 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
