apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello
  name: hello
spec:
  containers:
  - image: bmuschko/nodejs-hello-world:1.0.0
    name: hello
    ports:
    - containerPort: 3000
      name: nodejs-port
    readinessProbe:
      httpGet:
        port: nodejs-port
        path: /
      initialDelaySeconds: 2
    livenessProbe:
      initialDelaySeconds: 5
      periodSeconds: 8
      httpGet:
        path: /
        port: nodejs-port
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
